import time
import chromedriver_binary
from selenium import webdriver
from testparts_module import kokyakuopen,Login
from test_module import HoujinTourokuTest,TorihikisakiTourokuTest,SeikyuSakiTourokuTest,TorimatomeKigyouHozonTest
from test_module import HoujinSakuzyoTest,HoujinHensyuTest
from common_module import TestDataObject,reportexcel
from testcode_module import postslacktest


postslacktest.execute()